### DISCUSSION TITLE
Integration into the Flux bootstrap workflow

### DISCUSSION THREAD

**Discussion by chanwit** [flux-iac/tofu-controller#316] [Ideas]
We would like to integrate an installation of TF-controller into the Flux bootstrap workflow.

For example, we did Flux bootstrap with the following command.
```
export GITHUB_TOKEN=<token>
flux bootstrap github \
  --owner=org \
  --repository=my-repo \
  --personal \
  --branch=main \
  --path=./cluster/default
```

Then we need to tweak `kustomization.yaml` by adding these patches (https://github.com/fluxcd/website/pull/1099) *without* messing the current content.
We would need a help from KYAML to do so.

```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - gotk-components.yaml
  - gotk-sync.yaml
patches:
  - patch: |
      - op: add
        path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/eventSources/items/properties/kind/enum/-
        value: Terraform
    target:
      kind: CustomResourceDefinition
      name:  alerts.notification.toolkit.fluxcd.io
  - patch: |
      - op: add
        path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/resources/items/properties/kind/enum/-
        value: Terraform
    target:
      kind: CustomResourceDefinition
      name:  receivers.notification.toolkit.fluxcd.io
  - patch: |
      - op: add
        path: /rules/-
        value:
          apiGroups: [ 'infra.contrib.fluxcd.io' ]
          resources: [ '*' ]
          verbs: [ '*' ]
    target:
      kind: ClusterRole
      name:  crd-controller
```
