### DISCUSSION TITLE
Set chart version to application version

### DISCUSSION THREAD

**Discussion by onedr0p** [flux-iac/tofu-controller#452] [Ideas]
Hi 👋🏼 

It would be great for automation purposes if the version of the chart matched the version of the application. I deployed the helm chart with `installCRDs: false`. I am installing CRDs via a `GitRepository` and a `Fluxtomization` so the helm chart and crds versions can be managed by [Renovate](https://github.com/renovatebot/renovate).

The reason for doing this is so I can contain the HelmRelease and Terraform CRs in the same `Fluxtomization`.

In simplest terms if you try to apply the following Kustomization for the first time it will fail because the CRDs are not installed yet and I want a automated way to manage versions of the CRDs and Helm Chart in a single `Fluxtomization`.

```yaml
# ./kustomization.yaml
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helm-release.yaml
  - terraforms.yaml
```

---

```yaml
# ./helm-release.yaml
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tf-controller
  namespace: flux-system
spec:
  interval: 15m
  chart:
    spec:
      chart: tf-controller
      version: v0.13.1
      sourceRef:
        kind: GitRepository
        name: tf-controller
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    installCRDs: true
```

---

```yaml
# ./terraforms.yaml
---
apiVersion: infra.contrib.fluxcd.io/v1alpha1
kind: Terraform
metadata:
  name: cloudflare
  namespace: flux-system
spec:
  approvePlan: auto
  interval: 12h
  path: ./terraform/cloudflare
  sourceRef:
    kind: OCIRepository
    name: terraform-cloudflare-oci
    namespace: flux-system
  backendConfig:
    disable: true
  cliConfigSecretRef:
    name: tfe-cli-config
  varsFrom:
    - kind: Secret
      name: cloudflare-vars
  writeOutputsToSecret:
    name: cloudflare-outputs
```

---

An full example can be seen here with Kyverno:

* [Kyverno GitRepository and the Fluxtomization applying their CRDs](https://github.com/onedr0p/home-ops/blob/a9b0c58e155a789f02b82788b1b2444bf00a693d/cluster/flux/config/flux-prereqs.yaml#L62-L91).

* [The apps `Fluxtomization` which under it has Kyverno CRs and the Kyverno `HelmRelease`](https://github.com/onedr0p/home-ops/blob/a9b0c58e155a789f02b82788b1b2444bf00a693d/cluster/flux/apps.yaml).

* The [Kyverno `HelmRelease`](https://github.com/onedr0p/home-ops/blob/a9b0c58e155a789f02b82788b1b2444bf00a693d/cluster/apps/kube-tools/kyverno/helm-release.yaml) and [the CRs ](https://github.com/onedr0p/home-ops/tree/a9b0c58e155a789f02b82788b1b2444bf00a693d/cluster/apps/kube-tools/kyverno/policies)which are all under the same apps `Fluxtomization`

* The [pull request](https://github.com/onedr0p/home-ops/pull/4115) where you can see the versions being updated on a new release.

Thanks!
