### DISCUSSION TITLE
Support for complex structures in values

### DISCUSSION THREAD

**Discussion by akselleirv** [flux-iac/tofu-controller#485] [Q&A] [answered]
Hello,

I'm using the values functionality to get some inputs to my Terraform module, but I'm not able to parse an array. My Terraform CRD looks like this:

The `other-module` outputs this:
```
output "clusters" {
  value = ["cluster-a", "cluster-b"]
}
```

```
apiVersion: infra.contrib.fluxcd.io/v1alpha1
kind: Terraform
metadata:
  name: example
  namespace: flux-system
spec:
  approvePlan: auto
  path: ./terraform/modules/my-module
  sourceRef:
    kind: GitRepository
    name: my-repo
    namespace: flux-system
  destroyResourcesOnDeletion: true
  dependsOn:
    - name: other-module
  readInputsFromSecrets:
    - name: other-module-outputs
      as: other_module
  values:
    clusters: ${{ .other_module.clusters }}
```

And the `my-module` has the variable:
```
variable "values" {
  type = object({
    clusters = set(string)
  })
}
```

But I'm getting an parsing error. Is this suppose to happened, or is it not able to parse an array?
