### DISCUSSION TITLE
Is a map of object supported as input variable?

### DISCUSSION THREAD

**Discussion by aspx** [flux-iac/tofu-controller#546] [Q&A] [answered]
Hello, 

First of all, great work with this project!

Is a map of objects supported as input variable? I've already tries several ways of specifying the variable, but always getting "Invalid value for input variable". If someone can point me in the right direction, it would be great!

I've a terraform module with the bellow variable: 

```
variable "heartbeats" {
  type = map(object({
    name           = string
    description    = optional(string)
    interval_unit  = optional(string)
    interval       = optional(number)
    enabled        = optional(string)
    alert_message  = optional(string)
    alert_priority = optional(string)
    alert_tags     = optional(list(string))
  }))
}
```
In the terraform CR , I've the following: 

```
apiVersion: infra.contrib.fluxcd.io/v1alpha1
kind: Terraform
metadata:
  name: test 
  namespace: test
spec:
  interval: 1m
  approvePlan: auto
  destroyResourcesOnDeletion: false
  path: ./
  sourceRef:
    kind: GitRepository
    name: terraform-modules-test
    namespace: test
  vars:
  - name: heartbeats 
    value: | 
      {
      "test"={
        name="test"
        }
      }
```

During the plan I'm getting the error "Invalid value for input variable" 

```
Error: Invalid value for input variable

  on generated.auto.tfvars.json line 1:
   1: {"heartbeats":"{\n\"test\"={\n  name=\"test\"\n  }\n}\n"}

The given value is not suitable for var.heartbeats declared at
variables.tf:6,1-22: map of object required.
{"level":"error","ts":"2023-03-02T18:22:29.925Z","logger":"runner.terraform","msg":"error creating the plan","instance-id":"ec150056-fb66-42a2-8f48-bce1481961b4","error":"exit status 1\n\nError: Invalid value for input variable\n\n  on generated.auto.tfvars.json line 1:\n   1: {\"heartbeats\":\"{\\n\\\"test\\\"={\\n  name=\\\"test\\\"\\n  }\\n}\\n\"}\n\nThe given value is not suitable for var.heartbeats declared at\nvariables.tf:6,1-22: map of object required.\n"}
```

Thanks!

**Comment by chanwit** [comment, marked as answer]
Hi @aspx 
The controller supports YAML to HCL conversion so in your case please try:

```yaml
apiVersion: infra.contrib.fluxcd.io/v1alpha1
kind: Terraform
metadata:
  name: test 
  namespace: test
spec:
  interval: 1m
  approvePlan: auto
  destroyResourcesOnDeletion: false
  path: ./
  sourceRef:
    kind: GitRepository
    name: terraform-modules-test
    namespace: test
  vars:
  - name: heartbeats 
    value:
      test:
        name: test
```
