### DISCUSSION TITLE
option to write output to a configmap

### DISCUSSION THREAD

**Discussion by vSivarajah** [flux-iac/tofu-controller#551] [Ideas]
Has there been any discussion to enable writing output to a configmap?

We have a usecase where writing the output to configmap would be more beneficial than writing to secret, due to argocd being able to display the values in configmap but not secret for developers.

**Comment by chanwit** [comment]
hi @vSivarajah thank for for bringing this up!

Outputs may contain sensitive values. That's the main reason why outputs are written to a Secret.
Maybe we need a flag in the spec like `allowSensitiveOutputs` or something like that?

Let's discuss.

**Reply by vSivarajah** [reply]
By default we can assume that an output may contain sensitive values and in case you would want to output that to a secret you can instruct it in the Terraform CR. However, in cases where you know that the output is not a senstive value we would rather have it downstreamed to a configmap, because it is a viewable object in Argo GUI for example. 

As an example it could be something like this:

```
writeOutputs:
  - kind: Secret
     name: my-secret
     outputs:
      - my_sensitive_value
  - kind: ConfigMap
     name: my-configmap
     outputs:
     - hello_world
```
