### DISCUSSION TITLE
New Concept: ConfigProvider CR

### DISCUSSION THREAD

**Discussion by chanwit** [flux-iac/tofu-controller#746] [Ideas]
A concept of `ConfigProvider`

```yaml
apiVersion: infra.contrib.fluxcd.io/v1alpha3
kind: Terraform
metadata:
  name: aws-s3-bucket
  namespace: flux-system
spec:
  path: aws_s3_bucket
  values:
    bucket: my-tf-controller-test-bucket
    tags:
      Environment: Override Dev
      Name: Override My bucket
  configProviderRef:
    name: default
---
apiVersion: infra.contrib.fluxcd.io/v1alpha3
kind: ConfigProvider
metadata:
  name: default
  namespace: flux-system
spec:
  terraform:
    path: aws_s3_bucket
    values:
      bucket: my-tf-controller-test-bucket
      tags:
        Environment: Dev
        Name: My bucket
    sourceRef:
      kind: OCIRepository
      name: aws-package
    approvePlan: auto
    interval: 2m
    destroyResourcesOnDeletion: true
    writeOutputsToSecret:
      name: aws-s3-bucket-outputs
      outputs:
      - arn
      - bucket
    runnerPodTemplate:
      spec:
        env:
        - name: AWS_REGION
          value: us-west-100
        envFrom:
        - secretRef:
            name: aws-credentials
```
