### DISCUSSION TITLE
How can I see my plan ?

### DISCUSSION THREAD

**Discussion by da-ishi10** [flux-iac/tofu-controller#853] [Q&A]
I want to see my plan using tfctl with reference to the following.
https://docs.gitops.weave.works/docs/terraform/get-started/

```
apiVersion: infra.contrib.fluxcd.io/v1alpha2
kind: Terraform
metadata:
  name: helloworld
  namespace: flux-system
spec:
  interval: 1m
  planOnly: true
  path: ./
  storeReadablePlan: human
  sourceRef:
    kind: GitRepository
    name: helloworld
    namespace: flux-system
```

But I don't see the expected result.
How can I see it?
```
$ tfctl show plan -n flux-system helloworld
There is no plan pending.
```

Also, how can I see my plan in advance if:
`approvePlan: auto`
