### ISSUE TITLE
[BranchPlanner] Is it possible to generate a Plan in Json format in the BranchPlanner flow?

### ISSUE THREAD

**Issue by joaoarthurv** [flux-iac/tofu-controller#1228]
Good afternoon everyone, I hope you're all doing well.

I'm working on a project to set up a GitOps workflow, and after some research, I've chosen the following tools (Flux + TFController (BranchPlanner) + Jenkins).

The idea is that when a PR is opened, the BranchPlanner is executed, and it should be possible to capture the plan in Json format. This Json-formatted plan will be captured by Jenkins, where I'll perform some validations.

While studying the tool and following the [documentation](https://flux-iac.github.io/tofu-controller/), I noticed that when I open a PR, temporary PLANs are generated in ConfigMap, along with a secret related to the PLAN and another related to the TFState. So far, from what I could tell, neither of these is in Json format.

Currently, is it possible to capture the plan in Json format in the BranchPlanner flow?

-----

I've noticed that if I merge the PR and the Terraform has the `storeReadablePlan: json` attribute enabled, a plan is created in the secret in .json format. However, since I expect this Json before the Merge, this feature doesn't fit well with what I need.

If anyone has any suggestions, they are very welcome.

I appreciate the support in advance.

-----

```
apiVersion: infra.contrib.fluxcd.io/v1alpha2
kind: Terraform
metadata:
  name: pod-test
  namespace: tf-test
spec:
  serviceAccountName: tf-test
  interval: 3m
  approvePlan: auto
  branchPlanner:
    enablePathScope: true
  destroyResourcesOnDeletion: true
  refreshBeforeApply: true
  storeReadablePlan: json
  backendConfig:
    secretSuffix: pod-test
  path: ./project-test/infra/poc-tf/tf
  sourceRef:
    kind: GitRepository
    name: tf-test
    namespace: tf-test
```

```
resource "kubernetes_pod" "example" {
  metadata {
    name = "pod-test-json-validate-pr"
    namespace = "tf-test"
  }

  spec {
    container {
      image = "nginx:latest"
      name  = "nginx-container"
    }
  }
}
```
