### ISSUE TITLE
Branch planner does plan for all opened PRs in the repo despite on branch

### ISSUE THREAD

**Issue by hirenko-v** [flux-iac/tofu-controller#1263]
I have such gitrepo
```
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  annotations:
  name: flux-system
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: flux
  secretRef:
    name: flux-system
  timeout: 60s
  url: ssh://git@github.com/myorg/infrastructure.git
    ```
    
    and such Terraform
    
    ```
 apiVersion: infra.contrib.fluxcd.io/v1alpha2
kind: Terraform
metadata:
  name: example
  namespace: flux-system
spec:
  alwaysCleanupRunnerPod: true
  backendConfig:
    customConfiguration: "# Override"
  destroyResourcesOnDeletion: false
  interval: 1m0s
  path: ./terraform/example
  refreshBeforeApply: false
   serviceAccountName: tf-runner
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  storeReadablePlan: human
    ```
    
    and branch-planner config:
    ```
apiVersion: v1
data:
  resources: |-
  -  namespace: flux-system
  secretName: branch-planner-token
kind: ConfigMap
metadata:
  name: branch-planner
  namespace: flux-system
 ```
 
 and seems like it does plan for all open PRs despite on the repo config
 ```
   ref:
    branch: flux
    
    ```
    
    It doesn't happen with rc2 but rc3 and rc4 seems to be broken
