### ISSUE TITLE
Branch Planner Fails due to missing create & delete RBAC for gitrepositories

### ISSUE THREAD

**Issue by jaguer0** [flux-iac/tofu-controller#1274]
Recently enabled Branch Planner and it fails due to the default controller service account `system:serviceaccount:terraform:terraform-controller-tf-controller` not having the proper RBAC to create & delete gitrepositories. 

 Appears to be missing [here](https://github.com/flux-iac/tofu-controller/blob/9bab501e092c467a55eec7f546ff9d412fcab8ac/charts/tf-controller/templates/rbac.yaml#L159) 

>{"level":"error","ts":"2024-04-03T17:06:47.281Z","logger":"polling-server","msg":"failed to reconcile Terraform object for PR","version":"","sha": "","terraform":"terraform-platform","namespace":"terraform","source":"tf-repo-platform","PR ID":"8","error":"unable to reconcile Source for Terraform object terraform-platform-pr-8 in the namespace terraform: reconcile failed for Source tf-repo-platform-b17b79cff6f8207325b9-pr-8 in the namespace terraform: gitrepositories.source.toolkit.fluxcd.io is forbidden: User \"system:serviceaccount:terraform:terraform-controller-tf-controller\" cannot create resource \"gitrepositories\" in API group \"source.toolkit.fluxcd.io\" in the namespace \"terraform\""}

HelmRelease 
```
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: terraform-controller
  namespace: terraform
spec:
  serviceAccountName: flux-tf
  interval: 1h
  chart:
    spec:
      version: '0.16.0-rc.4'
      chart: tf-controller
      sourceRef:
        kind: HelmRepository
        name: terraform-chart
      interval: 12h
  install:
    crds: CreateReplace
    timeout: 10m
  upgrade:
    crds: CreateReplace
    timeout: 10m
  values:
    serviceAccount:
      annotations:
        eks.amazonaws.com/role-arn: arn:xyz
    runner:
      serviceAccount:
        name: tf-runner
        annotations:
          eks.amazonaws.com/role-arn: arn:xyz
    branchPlanner:
      enabled: true
      ```

**Comment by mnencia** [comment]
You can workaround the issue by using a post renderer:

```
  postRenderers:
  - kustomize:
      patches:
      - target:
          group: rbac.authorization.k8s.io
          version: v1
          kind: ClusterRole
          name: tf-manager-role
        patch: |
          - op: add
            path: /rules/5/verbs/-
            value: create
          - op: add
            path: /rules/5/verbs/-
            value: delete
```
