### ISSUE TITLE
Namesapce flux-system is always needed (helm install)

### ISSUE THREAD

**Issue by krone-rose** [flux-iac/tofu-controller#1286]
Currently I want install the tofu controller in the namespace flux (not flux-system). FluxCD is installed in the namespace flux2 (Kubermatic default)
When I change the namespace to this new namespace and didn't create the flux-system namespace manual I become the following failure:

```
   Normal   HelmChartCreated  16s   helm-controller  Created HelmChart/flux/flux-tf-controller with SourceRef 'HelmRepository/flux/tf-controller'                                                                │
│   Warning  InstallFailed     12s   helm-controller  Helm install failed for release flux/tf-controller with chart tf-controller@0.16.0-rc.4: 2 errors occurred:                                                 │
│            * namespaces "flux-system" not found                                                                                                                                                                 │
│            * namespaces "flux-system" not found                                                                                                                                                                 │
│  
```                                                

After manual create the flux-system namespace and check which resources are created I see the serviceaccount tf-runner, also created in the changed namespace flux. 
After a short look on the helm code I think the failure is located here:
https://github.com/flux-iac/tofu-controller/blob/main/charts/tofu-controller/templates/_helpers.tpl
```
{{/*
Create a unique list of runner allowed namespaces
*/}}
{{- define "tofu-controller.runner.allowedNamespaces" -}}
{{- $allowedNamespaces := append .Values.runner.serviceAccount.allowedNamespaces .Release.Namespace -}}
**{{- $allowedNamespaces := append $allowedNamespaces "flux-system" -}}**
{{- $allowedNamespaces = $allowedNamespaces | uniq -}}
{{ toJson $allowedNamespaces }}
{{- end }}
```

Here is my HelmRelease code, based on your template:
```
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: tf-controller
spec:
  chart:
    spec:
      chart: tf-controller
      sourceRef:
        kind: HelmRepository
        name: tf-controller
      version: '0.16.0-rc.4'
  interval: 1h0s
  releaseName: tf-controller
  targetNamespace: flux
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  values:
    replicaCount: 1
    concurrency: 24
    resources:
      limits:
        cpu: 1000m
        memory: 2Gi
      requests:
        cpu: 400m
        memory: 64Mi
#    caCertValidityDuration: 24h
#    certRotationCheckFrequency: 30m
    image:
      tag: v0.16.0-rc.4
    runner:
      image:
        tag: v0.16.0-rc.4
```
