### ISSUE TITLE
TF-Runner stuck in Terminating state

### ISSUE THREAD

**Issue by kaspertng** [flux-iac/tofu-controller#1291]
Hello there!

Our tf-runner executes successfully but the pod get stuck in `Terminating` state. There is a finalizer attached

```
apiVersion: v1
kind: Pod
metadata:
  finalizers:
  - foregroundDeletion
  name: tf-runner
  namespace: foobar
  ...
...
```

When I remove the finalizer manually the pod gets cleaned up. 
To my understanding this is the expected behaviour as `foregroundDeletion` signals Kubernetes to wait for dependants to be cleaned up before deleting this resource.

**My question**: Who sets the finalizer and why is it not removed automatically?

Thank you very much for your help :)
