### ISSUE TITLE
Finalizer remains despite dependency was deleted

### ISSUE THREAD

**Issue by greenu** [flux-iac/tofu-controller#1293]
**tf-controller 0.15.1**

I have noticed that some resources that have dependency are stuck in deletion due to controller doesn't update finalizer
```
test-ns       test-vpc                  False   Deletion in progress, but blocked. Please delete test-rds-testdb1 to resume ...               9d
```
However tf resource test-rds-testdb1 was deleted successfully but finalizer is still there in `test-vpc`:

```
apiVersion: infra.contrib.fluxcd.io/v1alpha2
kind: Terraform
metadata:
  annotations:
    createdAt: "2024-04-30T03:58:24Z"
    updatedAt: "2024-04-30T04:02:34Z"
  creationTimestamp: "2024-04-30T03:58:28Z"
  deletionGracePeriodSeconds: 0
  deletionTimestamp: "2024-04-30T04:53:57Z"
  finalizers:
  - finalizers.tf.contrib.fluxcd.io
  - tf.dependency.of.test-rds-testdb1
  name: test-vpc
```
