### ISSUE TITLE
Terraform does not send recovery alert

### ISSUE THREAD

**Issue by hirenko-v** [flux-iac/tofu-controller#1330]
Hi team.
I have following alert configured for github provider

```
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Alert
metadata:
  annotations:
  name: github-status
  namespace: flux-system
spec:
  eventSeverity: info
  eventSources:
  - kind: Kustomization
    name: '*'
  - kind: Terraform
    name: '*'
  providerRef:
    name: github-status
 ```
 
 In underlying kustomization I have `healthCheck` configured and point to terraform resources.
 
 When terraform fails I have git commit status with failure message from `Terraform` and from `Kustomization`.
 But when `Terraform` is recovered from failure I have commit status update to successful just from `Kustomization`. Commit status from`Terraform` remains failed despite on the fact that error has been resolved and `Terraform` is  in `Ready` state.
