### ISSUE TITLE
[FEATURE] Add ability to configure resource requests and limits for the runner container

### ISSUE THREAD

**Issue by ahmadbabaeimoghadam** [flux-iac/tofu-controller#1491]
## Description 

Currently, the runner container in tofu-controller does not support the configuration of resource requests and limits (CPU and memory). This feature is critical for environments where resource allocation needs to be tightly managed.

## Proposal

Introduce a mechanism to allow users to set CPU and memory resource requests and limits for the runner container via configuration.

## Suggested Implementation

1. Extend the controller’s configuration schema to include resource parameters (e.g., resources.requests and resources.limits).
2. Update the runner container’s pod spec to apply the specified resource values during pod creation.
3. Provide clear documentation and examples to guide users on how to set these values.

## Example Configuration

```yaml
runnerPodTemplate:
  spec:
    resources:
      requests:
        cpu: "500m"
        memory: "256Mi"
      limits:
        cpu: "1"
        memory: "512Mi"
```

## Use Cases

1. Users can ensure the runner container has sufficient resources to operate efficiently.
2. Prevent resource overuse by setting upper limits, enhancing cluster stability.

## Additional Notes

- Please ensure that existing setups without this configuration remain unaffected (backward compatibility).
- This feature should be optional and only apply when users define the resource parameters.

**Comment by akselleirv** [comment]
Hello @ahmadbabaeimoghadam,

Configuring resources like you have done in your example configuration is possible in the Terraform spec.

Example:
```
apiVersion: infra.contrib.fluxcd.io/v1alpha2
kind: Terraform
metadata:
  name: sample
spec:
  ...
  runnerPodTemplate:
    spec:
      resources:
        limits:
          cpu: "1"
          memory: 1Gi
        requests:
          cpu: 250m
          memory: 512Mi
```
