### ISSUE TITLE
Error when pulling a referenced TF module

### ISSUE THREAD

**Issue by mrybson** [flux-iac/tofu-controller#1506]
Hi All,

The terraform code to be applied is referencing another repo (module). I am getting authentication error when trying to pull this referenced module. 

tf-controller logs output:

`Could not download module "kvault" (main.tf:1) source code from
"git::https://github.com/my-org/terraform-azurerm-keyvault.git?ref=2.0.1":
error downloading
'https://github.com/my-org/terraform-azurerm-keyvault.git?ref=2.0.1':
/usr/bin/git exited with 128: Cloning into '.terraform/modules/kvault'...
fatal: could not read Username for 'https://github.com': No such device or
address
`

my target Terraform code:

```
module "kvault" {
  source = "git::https://github.com/my-org/terraform-azurerm-keyvault.git?ref=2.0.1"
  tenant_id = "xxx"
  resource_group_name = "yyy"
  azure_region = "northeurope"
  key_vault_name = "kv-team-a"
  ......
  }
```

- I created separate GitRepository object representing this referenced module, but it didn't help.
- How to make it work?
- Please note that I might want to have multiple references to different modules versions at the same time, across different terraform 'main' repositories

**Comment by mrybson** [comment]
I made it work like this:

```
apiVersion: v1
kind: Secret
metadata:
  name: git-netrc
  namespace: flux-system
type: Opaque
stringData:
  .netrc: |-
    machine github.com
      login git
      password github_pat_12345
```

and then 

```
apiVersion: infra.contrib.fluxcd.io/v1alpha2
kind: Terraform
metadata:
  name: tf-demo
  namespace: flux-system
spec:
  interval: 2m
  approvePlan: auto
  # The Git repository that contains your main Terraform code
  sourceRef:
    kind: GitRepository
    name: main-terraform-repo
    namespace: flux-system
  path: "./"

  runnerPodTemplate:
    spec:
      # 1) Define a volume from the Secret above
      volumes:
        - name: netrc-volume
          secret:
            secretName: git-netrc

      # 2) Mount that volume into /home/runner/.netrc
      volumeMounts:
        - name: netrc-volume
          mountPath: /home/runner/.netrc
          subPath: .netrc
          readOnly: true

      # 3) Set HOME so Git sees ~/.netrc
      env:
        - name: HOME
          value: /home/runner
```

but is there any other, simpler way?
