### ISSUE TITLE
Rename Variables in varsFrom doesnt support objects

### ISSUE THREAD

**Issue by KarstenSiemer** [flux-iac/tofu-controller#1514]
Hi!

Thanks again for the great work on this controller.

The problem I am facing is that the varsFrom renaming feature doesn't support setting object values which are nested inside a terraform variable, but only supports string type variables.

Example:

Inside module:
```hcl
variable "helm" {
  type = object({
    name          = optional(string, "test")
    namespace     = optional(string, "test")
    registry = optional(object({
      url    = optional(string, null)
      secret = optional(string, null)
    }), {})
  })
  default     = {}
  nullable    = false
}
```

Using vars I can do something like this:

```yaml
apiVersion: infra.contrib.fluxcd.io/v1alpha2
kind: Terraform
...
spec:
  vars:
  - name: helm
    value:
      registry:
        url: my-registry.org
```

Which correctly results in the following:

generated.auto.tfvars.json:

```json
{"helm":{"registry":{"url":"my-registry.org"}}}
```

I now want to set helm.registry.secret using a kubernetes secret.
So I would do the following:

```yaml
apiVersion: infra.contrib.fluxcd.io/v1alpha2
kind: Terraform
...
spec:
  varsFrom:
  - kind: Secret
    name: oci-registry
    varsKeys:
    - .dockerconfigjson:helm.registry.secret
```

This however results in 

generated.auto.tfvars.json:

```json
{"helm.registry.secret": "secretValue"}
```

Which will not actually set that object value during tofu plan.
And due to the chosen separator of `:` it is not possible to pass any value which would result in the desired structure of  

```json
{"helm":{"registry":{"secret":"secretValue"}}}
```

After it was marshalled by json2.

[server_generate_tf_vars.go](https://github.com/flux-iac/tofu-controller/blob/main/runner/server_generate_tf_vars.go):

```golang
if strings.Contains(pattern, ":") {
  parts := strings.Split(pattern, ":")
```

I do misunderstand something and this is somehow possible?
It is very tough to fix I'd say, as the targets could be lists, maps or even any.
If we'd allow a different seperator, we could stay downwards compatible but pass in json as target key:

```yaml
apiVersion: infra.contrib.fluxcd.io/v1alpha2
kind: Terraform
...
spec:
  varsFrom:
  - kind: Secret
    name: oci-registry
    varsKeys:
    - .dockerconfigjson!{"helm":{"registry":{"secret"}}}
      separator: !
```

this would be invalid json however as there is no key.
I can't really think about a universally correct way to handle this, probably its the best how it is currently implemented.
All tofu input vars have a distinct key, to which one can rename. The value and type must be present in the datasource though.
So I need a new secret were the secret is present under the structure of the target input value and what I am trying to do is not supported.
A different implementation on the module side probably makes to most sense, to not create the imagePullSecret by tofu but just use the k8s secret which is used as a source here

I'd create the issue though just to document the limitation and then close it.
