### ISSUE TITLE
Branch planner fails due to insufficient privileges to create GitRepository object

### ISSUE THREAD

**Issue by mrybson** [flux-iac/tofu-controller#1516]
Hello
I just created fresh installation of Flux + Tofu controller with Branch Planner enabled. I follow the guide: https://flux-iac.github.io/tofu-controller/branch-planner/branch-planner-getting-started/ 

Once I open PR, that's what I get in the planner controller logs:

{"level":"error","ts":"2025-01-31T10:11:14.172Z","logger":"polling-server","msg":"failed to reconcile Terraform object for PR","version":"","sha":"","terraform":"product-a-tf-config","namespace":"flux-system","source":"product-a-git-repo","PR ID":"2",
"error":"unable to reconcile Source for Terraform object product-a-tf-config-pr-2 in the namespace flux-system: reconcile failed for Source product-a-git-repo-274fa63f241dc5005619-pr-2 in the namespace flux-system: gitrepositories.source.toolkit.fluxcd.io is **forbidden: User \"system:serviceaccount:flux-system:tf-controller\" cannot create resource \"gitrepositories\" in API group \"source.toolkit.fluxcd.io\" in the namespace \"flux-system\""**}

Is there anything I am missing in my configuration?

**Comment by mrybson** [comment]
I fixed it by adding a role and a binding:

role:

```
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: flux-system
  name: tf-controller-gitrepo-role
rules:
  - apiGroups:
      - source.toolkit.fluxcd.io
    resources:
      - gitrepositories
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
```

binding:

```
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tf-controller-gitrepo-binding
  namespace: flux-system
subjects:
  - kind: ServiceAccount
    name: tf-controller
    namespace: flux-system
roleRef:
  kind: Role
  name: tf-controller-gitrepo-role
  apiGroup: rbac.authorization.k8s.io

```
