### ISSUE TITLE
The CustomResourceDefinition "terraforms.infra.contrib.fluxcd.io" is invalid: metadata.annotations: Too long: must have at most 262144 bytes

### ISSUE THREAD

**Issue by jlewi** [flux-iac/tofu-controller#1533]
When I tried to deploy TOFU I ran into the error.

```
The CustomResourceDefinition "terraforms.infra.contrib.fluxcd.io" is invalid: metadata.annotations: Too long: must have at most 262144 bytes
```

I think this is because the CRD definition is too long. To work around this I simply deleted the older versions (v1alpha1) since I didn't need this.

I did this using kustomize with a patch.

```
patches:
  - target:
      group: apiextensions.k8s.io
      version: v1
      kind: CustomResourceDefinition
      name: terraforms.infra.contrib.fluxcd.io
    patch: |-
      - op: remove
        path: /spec/versions/0
```

Purpose of this issue is just to document it in case others run into it.
