### ISSUE TITLE
[BUG] Branch Planner generate more than 1 Plan in Pull Request when I have 3 Kind: Terraform with one GitRepository

### ISSUE THREAD

**Issue by kachi-app** [flux-iac/tofu-controller#1555]
Issues:
I created a GitRepository with 3 Terraform Resource references to it. All of them refers to different path, when I create a PR in a path let's say './modules/keycloak/oidc_providers`, the Branch planner will create 3 runner pods, and each of them will comment to the PR I created.

```
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: branch-planner
  namespace: flux-system
spec:
  interval: 30s
  url: https://github.com/[ORG_NAME]/[REPO_NAME]
  ref:
    branch: main
  secretRef:
    name: branch-planner-github-token
---
apiVersion: infra.contrib.fluxcd.io/v1alpha2
kind: Terraform
metadata:
  name: keycloak-oidc-providers
  namespace: flux-system
spec:
  approvePlan: auto
  storeReadablePlan: "human"
  interval: 1m
  path: ./modules/keycloak/oidc_providers
  sourceRef:
    kind: GitRepository
    name: branch-planner
    namespace: flux-system
  dependsOn:
    - name: "keycloak-realm"
  vars:
    - name: kc_provider
      value: "xxx"
  varsFrom:
    - kind: ConfigMap
      name: realm-oidc-providers-configmap
    - kind: Secret
      name: realm-oidc-providers-secret
---
apiVersion: infra.contrib.fluxcd.io/v1alpha2
kind: Terraform
metadata:
  name: keycloak-authentication-config
  namespace: flux-system
spec:
  approvePlan: auto
  storeReadablePlan: "human"
  interval: 1m
  path: ./modules/keycloak/authentication
  sourceRef:
    kind: GitRepository
    name: branch-planner
    namespace: flux-system
  vars:
    - name: kc_provider
      value: "xxx"
  varsFrom:
    - kind: ConfigMap
      name: realm-auth-configmap
---
apiVersion: infra.contrib.fluxcd.io/v1alpha2
kind: Terraform
metadata:
  name: keycloak-realm
  namespace: flux-system
spec:
  approvePlan: auto
  storeReadablePlan: "human"
  interval: 1m
  path: ./modules/keycloak/realm
  sourceRef:
    kind: GitRepository
    name: branch-planner
    namespace: flux-system
  vars:
    - name: kc_provider
      value: "xxx"
  varsFrom:
    - kind: ConfigMap
      name: realm-configmap
```

Here is the Screenshoot:

<img width="789" alt="Image" src="https://github.com/user-attachments/assets/f55ca87b-fdbf-4c5d-ab97-2e44b2d7dc42" />

Expected Results: 
Only path that have changes should generate runner pods

**Comment by kachi-app** [comment]
Solved with:
```
  branchPlanner:
    enablePathScope: true
```

```
apiVersion: infra.contrib.fluxcd.io/v1alpha2
kind: Terraform
metadata:
  name: keycloak-openid-client
  namespace: flux-system
spec:
  approvePlan: auto
  storeReadablePlan: "human"
  **branchPlanner:
    enablePathScope: true**
  interval: 1m
  path: ./modules/keycloak/openid_client
```
