### ISSUE TITLE
Input name mapping

### ISSUE THREAD

**Issue by caspervk** [flux-iac/tofu-controller#244]
Like [output name mapping](https://weaveworks.github.io/tf-controller/use_tf_controller/to_provision_resources_and_obtain_outputs/), it would sometimes be useful to be able to rename inputs too:
```yaml
  varsFrom:
  - kind: Secret
    name: my-secret
    varsKeys:
    - old_name:new_name
    - some_name
```
